//Ejercicio 1: Añadir personajes a una lista
//Tienes una lista de personajes de videojuegos ["Link", "Zelda"]. 
let videojuegos = ["Link", "Zelda"];

//Agrega los personajes "Mario" y "Luigi" al final de la lista utilizando el método adecuado.
videojuegos.push ("Mario", "Luigi");

//Luego, muestra el array actualizado.
console.log('Los personajes de videojuegos en la lista son: ', videojuegos);
